// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RatingAPI.Data;

namespace RatingAPI.Migrations
{
    [DbContext(typeof(RatingContext))]
    partial class RatingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("RatingAPI.Model.Rating", b =>
                {
                    b.Property<Guid>("VetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("RatePoints")
                        .HasColumnType("double");

                    b.Property<int>("UserCount")
                        .HasColumnType("int");

                    b.HasKey("VetId");

                    b.ToTable("Rate");
                });
#pragma warning restore 612, 618
        }
    }
}
